name: regiosqm-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask
  - numpy
  - boost-cpp==1.72.0 # rdkit bug https://github.com/rdkit/rdkit/issues/4987
  - rdkit
  - rmsd
  - scipy
  - tqdm
# dev
  - pre-commit
